perl -pi -e "s/SW_0/SW_00//" FXTal*
perl -pi -e "s/SW_1/SW_01//" FXTal*
perl -pi -e "s/SW_2/SW_02/" FXTal*
perl -pi -e "s/SW_3/SW_03/" FXTal*
perl -pi -e "s/SW_4/SW_04/" FXTal*
perl -pi -e "s/SW_5/SW_05/" FXTal*
perl -pi -e "s/SW_6/SW_06/" FXTal*
perl -pi -e "s/SW_7/SW_07/" FXTal*
perl -pi -e "s/SW_8/SW_08/" FXTal*
perl -pi -e "s/SW_9/SW_09/" FXTal*
perl -pi -e "s/SW_A1/SW_10/" FXTal*
perl -pi -e "s/SW_B1/SW_11/" FXTal*
perl -pi -e "s/SW_BSLS1/SW_12/" FXTal*
perl -pi -e "s/SW_BSPC1/SW_13/" FXTal*
perl -pi -e "s/SW_C1/SW_14/" FXTal*
perl -pi -e "s/SW_CAPS1/SW_15/" FXTal*
perl -pi -e "s/SW_COMM1/SW_16/" FXTal*
perl -pi -e "s/SW_D1/SW_17/" FXTal*
perl -pi -e "s/SW_DOT1/SW_18/" FXTal*
perl -pi -e "s/SW_E1/SW_19/" FXTal*
perl -pi -e "s/SW_ENT1/SW_20/" FXTal*
perl -pi -e "s/SW_EQL1/SW_21/" FXTal*
perl -pi -e "s/SW_ESC1/SW_22/" FXTal*
perl -pi -e "s/SW_F10/SW_23/" FXTal*
perl -pi -e "s/SW_F11/SW_24/" FXTal*
perl -pi -e "s/SW_F1/SW_25/" FXTal*
perl -pi -e "s/SW_F2/SW_26/" FXTal*
perl -pi -e "s/SW_F3/SW_27/" FXTal*
perl -pi -e "s/SW_F4/SW_28/" FXTal*
perl -pi -e "s/SW_F5/SW_29/" FXTal*
perl -pi -e "s/SW_F6/SW_30/" FXTal*
perl -pi -e "s/SW_F7/SW_31/" FXTal*
perl -pi -e "s/SW_F8/SW_32/" FXTal*
perl -pi -e "s/SW_F9/SW_33/" FXTal*
perl -pi -e "s/SW_FN1/SW_34/" FXTal*
perl -pi -e "s/SW_G1/SW_35/" FXTal*
perl -pi -e "s/SW_H1/SW_36/" FXTal*
perl -pi -e "s/SW_I1/SW_37/" FXTal*
perl -pi -e "s/SW_J1/SW_38/" FXTal*
perl -pi -e "s/SW_K1/SW_39/" FXTal*
perl -pi -e "s/SW_L1/SW_40/" FXTal*
perl -pi -e "s/SW_LALT1/SW_41/" FXTal*
perl -pi -e "s/SW_LBRC1/SW_42/" FXTal*
perl -pi -e "s/SW_LCTRL1/SW_43/" FXTal*
perl -pi -e "s/SW_LGUI1/SW_44/" FXTal*
perl -pi -e "s/SW_LSFT1/SW_45/" FXTal*
perl -pi -e "s/SW_M1/SW_46/" FXTal*
perl -pi -e "s/SW_MINS1/SW_47/" FXTal*
perl -pi -e "s/SW_N1/SW_48/" FXTal*
perl -pi -e "s/SW_NUBS1/SW_49/" FXTal*
perl -pi -e "s/SW_NUHS1/SW_50/" FXTal*
perl -pi -e "s/SW_O1/SW_51/" FXTal*
perl -pi -e "s/SW_OPEN1/SW_52/" FXTal*
perl -pi -e "s/SW_P10/SW_53/" FXTal*
perl -pi -e "s/SW_P11/SW_54/" FXTal*
perl -pi -e "s/SW_P12/SW_55/" FXTal*
perl -pi -e "s/SW_P13/SW_56/" FXTal*
perl -pi -e "s/SW_P14/SW_57/" FXTal*
perl -pi -e "s/SW_P15/SW_58/" FXTal*
perl -pi -e "s/SW_P16/SW_59/" FXTal*
perl -pi -e "s/SW_P17/SW_60/" FXTal*
perl -pi -e "s/SW_P18/SW_61/" FXTal*
perl -pi -e "s/SW_P19/SW_62/" FXTal*
perl -pi -e "s/SW_P1/SW_63/" FXTal*
perl -pi -e "s/SW_P20/SW_64/" FXTal*
perl -pi -e "s/SW_P21/SW_65/" FXTal*
perl -pi -e "s/SW_P2/SW_66/" FXTal*
perl -pi -e "s/SW_P3/SW_67/" FXTal*
perl -pi -e "s/SW_P4/SW_68/" FXTal*
perl -pi -e "s/SW_P5/SW_69/" FXTal*
perl -pi -e "s/SW_P6/SW_70/" FXTal*
perl -pi -e "s/SW_P7/SW_71/" FXTal*
perl -pi -e "s/SW_P8/SW_72/" FXTal*
perl -pi -e "s/SW_P9/SW_73/" FXTal*
perl -pi -e "s/SW_Q1/SW_74/" FXTal*
perl -pi -e "s/SW_QUOT1/SW_75/" FXTal*
perl -pi -e "s/SW_R1/SW_76/" FXTal*
perl -pi -e "s/SW_RALT1/SW_77/" FXTal*
perl -pi -e "s/SW_RBRC1/SW_78/" FXTal*
perl -pi -e "s/SW_RCTL1/SW_79/" FXTal*
perl -pi -e "s/SW_RGUI1/SW_80/" FXTal*
perl -pi -e "s/SW_RSFT1/SW_81/" FXTal*
perl -pi -e "s/SW_RSFT2/SW_82/" FXTal*
perl -pi -e "s/SW_S1/SW_83/" FXTal*
perl -pi -e "s/SW_SCLN1/SW_84/" FXTal*
perl -pi -e "s/SW_SLSH1/SW_85/" FXTal*
perl -pi -e "s/SW_SPC1/SW_86/" FXTal*
perl -pi -e "s/SW_SPC2/SW_87/" FXTal*
perl -pi -e "s/SW_SPC3/SW_88/" FXTal*
perl -pi -e "s/SW_T1/SW_89/" FXTal*
perl -pi -e "s/SW_TAB1/SW_90/" FXTal*
perl -pi -e "s/SW_U1/SW_91/" FXTal*
perl -pi -e "s/SW_V1/SW_92/" FXTal*
perl -pi -e "s/SW_W1/SW_93/" FXTal*
perl -pi -e "s/SW_X1/SW_94/" FXTal*
perl -pi -e "s/SW_Y1/SW_95/" FXTal*
perl -pi -e "s/SW_Z1/SW_96/" FXTal*
